# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:       ["tables"]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            '#PetriDish'
tagline:          'social media'
description:      'my works arount social media theme'
url:              http://www.facebook.com/atolmach

author:
  name:           'Alexander Tolmach'
  url:            http://www.facebook.com/atolmach

paginate:         10
paginate_path: "page:num"

# Custom vars
version:          0.0.0