# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:       ["tables"]
pygments:         true

# Permalinks
permalink:        /:year/:month/:title/

# Setup
title:            '#PetriDish'
tagline:          'social media'
description:      'my works arount social media theme'
url:              http://www.facebook.com/atolmach

author:
  name:           'Alexander Tolmach'
  url:            http://www.facebook.com/atolmach

paginate:         5

# Custom vars
version:          0.0.0